#!/usr/local/bin/ruby

require 'rubygems'
require 'oauth/consumer'
require 'yaml'

# puts "Please enter your client key, then hit Return."
consumer_key = "SBSlUEoMsrq2DzJ7wlf8Ng" # gets.chomp
#puts "Please enter your client secret, then hit Return."
consumer_secret = "y5v0loEQFBGreitRBlkg5QYKBNr7fedptgnWZzUKJM" #gets.chomp

begin
  consumer = OAuth::Consumer.new consumer_key, consumer_secret, { :site => "http://twitter.com/oauth/access_token", :proxy => "http://proxy-sjc-1.#{DOMAIN}.com:8080" }
  request_token = consumer.get_request_token
  puts "Please go to:\n#{request_token.authorize_url}\nin your browser. Click Authorize. Then copy the verifier code on that page.\n Type it here and hit Return here."
  verifier = gets.chomp.strip
  access_token = request_token.get_access_token(:oauth_verifier => verifier)
  credentials = {
    :consumer_key => consumer.key,
    :consumer_secret => consumer.secret,
    :access_token => access_token.token,
    :access_token_secret => access_token.secret
  }
  
  begin
    File.open('twitter_auth.yml', 'w') { |file| YAML.dump(credentials, file) }
    File.chmod(0600, 'twitter_auth.yml')
    puts "Your credentials have been saved in twitter_auth.yml in current directory."
  rescue
    puts "Couldn't save twitter_auth.yml. Check file and permissions."
  end
rescue
  puts "Couldn't authorize with Twitter. Check client credentials and retry."
  puts $!
end
