#!/usr/local/bin/ruby

require 'rubygems'
require 'oauth/consumer'
require 'yaml'

# puts "Please enter your client key, then hit Return."
consumer_key = "yc3FdwhqgmvMM5oHYJAuxw" # gets.chomp
#puts "Please enter your client secret, then hit Return."
consumer_secret = "A6dbrE39sObwiJ4iNq4vM5iMXqUGwOwfmanJOsnwfjs" #gets.chomp

begin
  consumer = OAuth::Consumer.new consumer_key, consumer_secret, { :site => "https://www.yammer.com", :proxy => "http://proxy-sjc-1.#{DOMAIN}.com:8080" }
  request_token = consumer.get_request_token
  puts "Please go to:\n#{request_token.authorize_url}\nin your browser. Click Authorize. Then copy the verifier code on that page.\n Type it here and hit Return here."
  verifier = gets.chomp.strip
  access_token = request_token.get_access_token(:oauth_verifier => verifier)
  credentials = {
    :consumer_key => consumer.key,
    :consumer_secret => consumer.secret,
    :access_token => access_token.token,
    :access_token_secret => access_token.secret
  }
  
  begin
    File.open('yammer_auth.yml', 'w') { |file| YAML.dump(credentials, file) }
    File.chmod(0600, 'yammer_auth.yml')
    puts "Your credentials have been saved in yammer_auth.yml in current directory."
  rescue
    puts "Couldn't save yammer_auth.yml. Check file and permissions."
  end
rescue
  puts "Couldn't authorize with Yammer. Check client credentials and retry."
  puts $!
end
